### ISSUE TITLE
Create  a homebridge plugin

### ISSUE THREAD

**Issue by duculete** [oroce/node-gree-smart#4]
Hello,

Any chance to create a Homebridge plugin to integrate this AC with Apple HomeKit?

https://github.com/nfarina/homebridge

Thanks,
Alex

**Comment by oroce** [comment]
I don't own apple devices except my mac so I'm not planning to, your best shot I guess is  using [home assistant](https://www.home-assistant.io/) with [this plugin](https://github.com/arthurkrupa/gree-hvac-mqtt-bridge) and home assistant can connect the ac to homebridge.
